# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    addToPath: true
    architecture: 'x64'
    
- script: python -m pip install Jinja2
  displayName: 'Install tools'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Content in directory: $env:SOURCE_DIR"
      Get-ChildItem -Path $env:SOURCE_DIR -Depth 4
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Microsoft Azure Internal Consumption (4591c181-b2c0-4a55-93a9-f759859a214b)'
    ScriptType: 'FilePath'
    ScriptPath: './downloadFromBlob.ps1'
    ScriptArguments: '$env:SOURCE_DIR'
    azurePowerShellVersion: 'LatestVersion'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Content in directory: $env:SOURCE_DIR"
      Get-ChildItem -Path $env:SOURCE_DIR -Depth 4
      
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'parameter_templates/update.py'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Content in directory: $env:SOURCE_DIR"
      Get-ChildItem -Path $env:SOURCE_DIR -Depth 4

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)'
    publishLocation: 'pipeline'